[project]
name = "py-shiny-starter-kit"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "shiny[theme] == 1.6.1",
    "shinywidgets == 0.8.1",
    "jinja2 ~= 3.1.6",
    "pandas ~= 3.0.2",
    "plotly[express] ~= 6.7.0",
    "undp-brand-yml[plotting] @ git+https://github.com/undp-data/undp-brand-yml.git@0.2.0",
    "undp-design-system @ git+https://github.com/UNDP-Data/py-shiny-components.git",
]

[project.optional-dependencies]
dev = [
    "pylint ~= 4.0.5",
    "isort ~= 8.0.1",
    "black ~= 26.3.1",
    "pytest ~= 9.0.3",
    "pytest-playwright ~= 0.7.2",
]
